import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';
import { DateTime } from 'luxon';
import { MdlZoomButtonComponent } from 'mdl-angular/zoom-button';
import { ConsistComponent } from '../../components/consist/consist.component';
import { CabinState, TrainModel } from '../../models/met';
import { OrientationPipe } from '../../pipes/orientation.pipe';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './diag.component.html',
  styleUrls: ['./diag.component.scss'],
  standalone: true,
  imports: [
    // NG
    CommonModule,
    MatIconModule,
    MdlZoomButtonComponent,
    ConsistComponent,
    OrientationPipe,
  ],
})
export class DiagComponent {
  protected reversed: boolean = false;
  protected train = signal<TrainModel>({
    composition: [
      {
        codeSerieMateriel: 'Z50000-8C-KVB',
        codeSerieMere: 'Z50000-8C',
        codeSerieRacine: 'Z50000',
        fleetName: 'Flotte Transilien Ligne H',
        lcnCode: 'Z50',
        numImmatEf: '01H',
        stf: 'SPN',
        tractionType: 'EMU',
        vehicles: [
          {
            numImmatEf: 'Z50001',
            friendlyName: 'V1',
            signalTechnicalPrefix: 'V1',
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
            coherencePosition: 1,
          },
          {
            numImmatEf: 'ZR501001',
            friendlyName: 'V2',
            signalTechnicalPrefix: 'V2',
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
            coherencePosition: 2,
          },
          {
            numImmatEf: 'ZZ502001',
            friendlyName: 'V3',
            signalTechnicalPrefix: 'V3',
            coherencePosition: 3,
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
          },
          {
            numImmatEf: 'ZR503001',
            friendlyName: 'V4',
            signalTechnicalPrefix: 'V4',
            coherencePosition: 4,
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
          },
          {
            numImmatEf: 'ZR504001',
            friendlyName: 'V5',
            signalTechnicalPrefix: 'V5',
            coherencePosition: 5,
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
          },
          {
            numImmatEf: 'ZR505001',
            friendlyName: 'V6',
            signalTechnicalPrefix: 'V6',
            coherencePosition: 6,
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
          },
          {
            numImmatEf: 'ZR506001',
            friendlyName: 'V7',
            signalTechnicalPrefix: 'V7',
            coherencePosition: 7,
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
          },
          {
            numImmatEf: 'Z50002',
            friendlyName: 'V8',
            signalTechnicalPrefix: 'V8',
            coherencePosition: 8,
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
          },
        ],
      },
      {
        codeSerieMateriel: 'Z50000-8C-KVB',
        codeSerieMere: 'Z50000-8C',
        codeSerieRacine: 'Z50000',
        fleetName: 'Flotte Transilien Ligne H',
        lcnCode: 'Z50',
        numImmatEf: '02H',
        stf: 'SPN',
        tractionType: 'EMU',
        vehicles: [
          {
            numImmatEf: 'Z50003',
            friendlyName: 'V1',
            signalTechnicalPrefix: 'V1',
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
            coherencePosition: 1,
          },
          {
            numImmatEf: 'ZR501003',
            friendlyName: 'V2',
            signalTechnicalPrefix: 'V2',
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
            coherencePosition: 2,
          },
          {
            numImmatEf: 'ZZ502003',
            friendlyName: 'V3',
            signalTechnicalPrefix: 'V3',
            coherencePosition: 3,
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
          },
          {
            numImmatEf: 'ZR503003',
            friendlyName: 'V4',
            signalTechnicalPrefix: 'V4',
            coherencePosition: 4,
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
          },
          {
            numImmatEf: 'ZR504003',
            friendlyName: 'V5',
            signalTechnicalPrefix: 'V5',
            coherencePosition: 5,
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
          },
          {
            numImmatEf: 'ZR505003',
            friendlyName: 'V6',
            signalTechnicalPrefix: 'V6',
            coherencePosition: 6,
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
          },
          {
            numImmatEf: 'ZR506003',
            friendlyName: 'V7',
            signalTechnicalPrefix: 'V7',
            coherencePosition: 7,
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
          },
          {
            numImmatEf: 'Z50004',
            friendlyName: 'V8',
            signalTechnicalPrefix: 'V8',
            coherencePosition: 8,
            acRooms: [],
            doors: [],
            bogie1: null,
            bogie2: null,
          },
        ],
      },
    ],
    mission: {
      misionNumber: '123456',
      missionCode: 'POVA',
      nextStation: 'Saint-Denis',
      previousOrCurrentStation: 'Paris Nord',
    },
    states: {
      '01H': {
        lastCommunication: DateTime.now().minus({ seconds: 5 }),
        geolocation: {
          latitude: 47.3819,
          longitude: 0.6867,
          altitude: null,
          orientation: null,
        },
        totalPassengers: 42,
        vehicleStates: {
          Z50001: <CabinState>{
            nbPassengers: 2,
            acRooms: {},
            cabinAcRoom: null,
            BP_URG: true,
            inService: true,
            Q_UM: false,
          },
        },
      },
    },
    weather: {
      localHumidityPercent: 70,
      localTemperatureCelsius: 15.1,
      type: 'cloudy',
      locality: 'Saint-Denis',
    },
  });

  public scale: number = 1;
}
